/* scope-styles.js — generate registry/styles.scoped.css from registry/styles.css.
   The unified host mounts the Database view inside .v-database in the SAME document
   as Charting + Analyse. Registry's styles.css is a full-page stylesheet: its
   `body`, `.btn`, and bare-tag rules would leak out and break the other surfaces.
   This transform prefixes every rule selector with `.v-database ` so nothing
   escapes the view, while leaving token/theme roots (:root, html[...]) global so
   the shared design tokens still resolve. `body` maps to `.v-database` (the view
   root). Run from app/: `node registry/scope-styles.js`. The sync regenerates it.

   Deliberately conservative — it understands strings, comments, @media/@supports
   (recurses), and @keyframes/@font-face/@page (emitted verbatim, never prefixed).  */
"use strict";
var fs = require("fs");
var path = require("path");

var SRC = path.join(__dirname, "styles.css");
var OUT = path.join(__dirname, "styles.scoped.css");
var SCOPE = ".v-database";

// Split a block of CSS into top-level tokens: either an at-rule/rule (with its
// braces) or stray text. Respects /* */ comments and "…" '…' strings.
function splitRules(css) {
  var out = [], i = 0, n = css.length;
  while (i < n) {
    // skip + capture leading whitespace/comments as their own passthrough token
    var start = i;
    // find the next "{" , "}" or ";" at depth 0, tracking comments/strings
    var depth = 0, sel = "";
    var body = null;
    var j = i;
    for (; j < n; j++) {
      var c = css[j];
      if (c === "/" && css[j + 1] === "*") { var e = css.indexOf("*/", j + 2); j = (e === -1 ? n : e + 1); continue; }
      if (c === '"' || c === "'") { var q = c; j++; while (j < n && css[j] !== q) { if (css[j] === "\\") j++; j++; } continue; }
      if (c === "@" && depth === 0) { /* at-rule — handled by brace/semicolon below */ }
      if (c === "{") {
        if (depth === 0) { sel = css.slice(i, j); body = { open: j }; }
        depth++;
        continue;
      }
      if (c === "}") {
        depth--;
        if (depth === 0 && body) { out.push({ type: "rule", sel: sel, inner: css.slice(body.open + 1, j), raw: css.slice(i, j + 1) }); i = j + 1; break; }
        continue;
      }
      if (c === ";" && depth === 0) { out.push({ type: "stray", raw: css.slice(i, j + 1) }); i = j + 1; break; }
    }
    if (j >= n) { if (i < n) { out.push({ type: "stray", raw: css.slice(i) }); } break; }
  }
  return out;
}

// Prefix a single selector list (comma-separated) with SCOPE, with the rules
// described in the header. Returns the rewritten selector list.
function scopeSelectorList(selList) {
  return selList.split(",").map(function (raw) {
    var s = raw.trim();
    if (!s) { return raw; }
    // leading combinator/whitespace preserved loosely; operate on trimmed form
    if (s === ":root") { return raw; }                 // token root — stays global
    if (/^html(\b|[.:#\[])/.test(s)) { return raw; }   // theme/root & html-context selectors stay global
    if (/^:where\(:root\)/.test(s)) { return raw; }
    if (/^body\b/.test(s)) {
      // body -> the view root; body.foo -> .v-database.foo ; body foo -> .v-database foo
      var rest = s.slice(4);
      return SCOPE + rest;
    }
    return SCOPE + " " + s;
  }).join(",");
}

function stripComments(s) { return s.replace(/\/\*[\s\S]*?\*\//g, ""); }

// Recurse into @media/@supports bodies; pass @keyframes/@font-face/@page through.
function transform(css) {
  return splitRules(css).map(function (tok) {
    if (tok.type === "stray") { return tok.raw; }
    var sel = stripComments(tok.sel).trim();   // comments between rules are decorative — drop before prefixing
    var at = sel.match(/^@([a-z-]+)/i);
    if (at) {
      var name = at[1].toLowerCase();
      if (name === "media" || name === "supports" || name === "container" || name === "layer" && /\{/.test(tok.raw)) {
        return tok.sel + "{" + transform(tok.inner) + "}";
      }
      // keyframes / font-face / page / anything else: emit verbatim (no prefixing)
      return tok.raw;
    }
    // ordinary style rule
    return scopeSelectorList(sel) + "{" + tok.inner + "}";
  }).join("");
}

var css = fs.readFileSync(SRC, "utf8");
var scoped = "/* GENERATED by registry/scope-styles.js — do not edit. Source: styles.css */\n" + transform(css);
fs.writeFileSync(OUT, scoped);
// tiny report
var leaks = (scoped.match(/(^|\})\s*(body|button|input|a|fieldset|legend)\s*[,{]/g) || []).filter(function (x) { return !/\.v-database/.test(x); });
console.log("wrote " + OUT + " (" + scoped.length + " bytes)");
console.log("unscoped bare-tag rules remaining (should be ~0):", leaks.length);
if (leaks.length) { console.log(leaks.slice(0, 10)); }
